### ISSUE TITLE
Adding cpp-httplib based bundle.

### ISSUE THREAD

**Issue by Pilipets** [Smertig/banana#10]
The purpose of this issue is to create a bundle based on the https://github.com/yhirose/cpp-httplib.

Overall, this is a great library similar to CPR but supports both clients, server connections and doesn't depend on the libcurl. Server-related or any other unused code can be easily deleted since the library is a one-header file only.

Why CPP-httlib?
1. Thread-safe access;
2. SSL, proxy, error-codes, timeout;
3. Extensive support and usage - 5.1k stars;
4. One-header only;

Here are some drawbacks of such addition:
1. Non-blocking requests aren't supported by default, but there exists a solution mentioned here(https://github.com/rtrahan504/cpp-httplib/tree/nonblocking_server) and here(https://github.com/yhirose/cpp-httplib/issues/875), which allows them. Adding blocking-only requests might be a good start.
2.  Overkill for telegram and banana purposes. Are you thinking of extending the existing `WinAPI` connector instead? Answering that, we don't need to use all the CPP-httplib in full, but simply extract the minimum needed for SSL, proxy, thread-safety, error-codes, timeouts until a custom replacement solution is available.
3. C++11 - there is a cpp17 branch in the dev state - https://github.com/yhirose/cpp-httplib/tree/cpp17.

**I am not claiming this is necessary, just thinking loudly and pointing out to such a library...**

**Comment by Smertig** [comment]
Good idea. `cpp-httplib` is quite popular, so it's worth implementing a connector based on it **if possible.** 

PR are welcome! We could start with blocking-only connector.
